name: Pest Tests with Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  pest-coverage:
    name: Pest Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: pcov
          extensions: dom, curl, fileinfo, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, pcov

      - name: Install dependencies
        run: |
          composer require "laravel/framework:13.*" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Prepare PHPUnit config
        run: cp phpunit.xml.dist phpunit.xml

      - name: Run Pest Tests with Coverage
        run: ./vendor/bin/pest --coverage --min=45 --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: coverage.xml
